_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 1
                - 41
                - 49
                - 71
                - 83
            "2":
                - 1
                - 41
                - 49
                - 71
                - 83
            "3":
                - 55
            "4": 3.12.7
            "5": 0.20.1
            "8":
                - 3
            "12": 0.20.1
            "13": windows-amd64
adam_beta1:
    value: 0.9
adam_beta2:
    value: 0.999
adam_epsilon:
    value: 1e-08
allow_tf32:
    value: false
checkpointing_steps:
    value: 20000
checkpoints_total_limit:
    value: null
criterion:
    value: mse
data_root:
    value: ./data/cities
data_source:
    value: ./data/cities/Bari/1
data_target:
    value: ./data/cities/Tokyo/1
dataloader_num_workers:
    value: 0
gradient_accumulation_steps:
    value: 1
gradient_checkpointing:
    value: false
interp:
    value: straight
is_independent_coupling:
    value: true
learning_rate:
    value: 0.0002
local_rank:
    value: -1
logging_dir:
    value: logs
lr_num_cycles:
    value: 1
lr_power:
    value: 1
lr_scheduler:
    value: constant
lr_warmup_steps:
    value: 500
max_grad_norm:
    value: 1
max_train_steps:
    value: 1000
mixed_precision:
    value: null
num_train_epochs:
    value: 334
output_dir:
    value: ./output
random_flip:
    value: true
report_to:
    value: wandb
resolution:
    value: 256
resume_from_checkpoint:
    value: null
sample_batch_size:
    value: 4
scale_lr:
    value: false
seed:
    value: null
source_distribution:
    value: normal
train_batch_size:
    value: 16
train_time_distribution:
    value: uniform
train_time_weight:
    value: uniform
use_ema:
    value: true
validation_epochs:
    value: 50
